spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://47.104.211.150/classtest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  freemarker:
    check-template-location: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**